name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Miniconda
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    # 3️⃣ Debug environment (opsional)
    - name: Debug Conda Environment
      run: |
        conda info
        conda list
        which python
        conda run -n mlflow-ci-env which mlflow

    # 4️⃣ Run MLflow Project di environment yang tepat
    - name: Run MLflow Project
      run: |
        conda run -n mlflow-ci-env mlflow run MLProject

    # 5️⃣ Upload MLflow artifacts
    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/mlruns

    # ====================
    #    Docker Build
    # ====================
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image using MLflow
      run: |
        conda run -n mlflow-ci-env mlflow models build-docker -m MLProject/mlruns/0/*/artifacts/model -n mirza-mlflow-ci:latest
        docker tag mirza-mlflow-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/mirza-mlflow-ci:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mirza-mlflow-ci:latest
